services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: slovny_zasobnik
      POSTGRES_PASSWORD: slovny_zasobnik
      POSTGRES_DB: slovny_zasobnik
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
